from pathlib import Path

from scholar_pdf.validator import (
    MIN_PDF_SIZE_BYTES,
    clean_invalid_pdf,
    is_valid_pdf,
    validate_pdf_structure,
)


def _write(tmp_path: Path, name: str, header: bytes, tail: bytes, size: int | None = None) -> Path:
    p = tmp_path / name
    payload = b"x" * max(0, (size or (MIN_PDF_SIZE_BYTES + 100)) - len(header) - len(tail))
    with open(p, "wb") as f:
        f.write(header + payload + tail)
    return p


def test_is_valid_pdf_true(tmp_path: Path):
    pdf_path = _write(tmp_path, "valid.pdf", b"%PDF-1.4\n", b"%%EOF\n")
    assert is_valid_pdf(pdf_path) is True
    assert clean_invalid_pdf(pdf_path) is True
    assert pdf_path.exists()


def test_is_valid_pdf_true_with_leading_garbage(tmp_path: Path):
    pdf_path = _write(tmp_path, "garbage.pdf", b"\x01\x02%PDF-1.7\nstream\n", b"%%EOF\n")
    assert is_valid_pdf(pdf_path) is True


def test_is_valid_pdf_true_within_trailer_window(tmp_path: Path):
    # %%EOF marker 4 KB before EOF is still within the 8 KB trailer window.
    pdf_path = _write(tmp_path, "window.pdf", b"%PDF-1.5\n", b"j" * 4096 + b"%%EOF\n")
    assert is_valid_pdf(pdf_path) is True


def test_is_valid_pdf_false_html(tmp_path: Path):
    html_path = tmp_path / "login.html"
    with open(html_path, "wb") as f:
        f.write(b"<!DOCTYPE html><html>...")

    assert is_valid_pdf(html_path) is False
    assert clean_invalid_pdf(html_path) is False
    assert not html_path.exists()  # Should be deleted


def test_is_valid_pdf_too_small(tmp_path: Path):
    small_path = tmp_path / "small.txt"
    with open(small_path, "wb") as f:
        f.write(b"%PD")

    assert is_valid_pdf(small_path) is False
    assert clean_invalid_pdf(small_path) is False
    assert not small_path.exists()


def test_is_valid_pdf_size_floor_rejects_small_valid_header(tmp_path: Path):
    """A %PDF- header smaller than the size floor is a stub/block page, not a real PDF."""
    stub_path = tmp_path / "stub.pdf"
    with open(stub_path, "wb") as f:
        f.write(b"%PDF-1.4\n")
        f.write(b"small stub payload" * 100)

    assert is_valid_pdf(stub_path) is False
    assert clean_invalid_pdf(stub_path) is False
    assert not stub_path.exists()


def test_is_valid_pdf_rejects_header_without_eof_trailer(tmp_path: Path):
    """A truncated download with a real header but no %%EOF trailer must fail."""
    pdf_path = _write(tmp_path, "truncated.pdf", b"%PDF-1.4\n", b"", size=MIN_PDF_SIZE_BYTES + 500)
    assert is_valid_pdf(pdf_path) is False
    clean_invalid_pdf(pdf_path)
    assert not pdf_path.exists()


def test_is_valid_pdf_rejects_forged_html_with_pdf_prefix(tmp_path: Path):
    """%PDF- bytes prepended to an HTML page pass a naive 5-byte check but must fail."""
    forged = tmp_path / "forged.pdf"
    with open(forged, "wb") as f:
        f.write(b"%PDF-1.4\n")
        f.write(b"<html><body>Checking your browser</body></html>" * 300)

    assert forged.stat().st_size > MIN_PDF_SIZE_BYTES
    assert is_valid_pdf(forged) is False


def test_is_valid_pdf_rejects_bad_version_string(tmp_path: Path):
    pdf_path = _write(tmp_path, "badver.pdf", b"%PDF-Foo\n", b"%%EOF\n")
    assert is_valid_pdf(pdf_path) is False


def test_validate_pdf_structure_parses_real_pdf(tmp_path: Path):
    """A genuinely parseable multi-page PDF (generated by pypdf itself) validates."""
    import io

    from pypdf import PdfWriter

    writer = PdfWriter()
    for _ in range(150):
        writer.add_blank_page(width=612, height=792)
    buffer = io.BytesIO()
    writer.write(buffer)

    p = tmp_path / "real.pdf"
    p.write_bytes(buffer.getvalue())
    assert p.stat().st_size > MIN_PDF_SIZE_BYTES
    assert is_valid_pdf(p) is True
    assert validate_pdf_structure(p) is True


def test_validate_pdf_structure_rejects_garbage(tmp_path: Path):
    """Binary signature passes but pypdf cannot make sense of the file."""
    p = _write(tmp_path, "garbage.pdf", b"%PDF-1.4\n", b"not really a pdf" + b"%%EOF\n")
    assert validate_pdf_structure(p) is False


def test_validate_pdf_structure_accepts_encrypted(tmp_path: Path, monkeypatch):
    """Files needing decryption parse fine after pypdf handles them."""
    from pypdf.errors import PdfReadError

    p = _write(tmp_path, "encrypted.pdf", b"%PDF-1.4\n", b"%%EOF\n")

    def fake_reader(stream, strict):
        raise PdfReadError("File has not been decrypted")

    monkeypatch.setattr("pypdf.PdfReader", fake_reader)
    assert validate_pdf_structure(p) is True